Repository Arquisoft/dede_en2b, pull requests merged in 2022-05, with the labels that each got.

#160 Tests for ProductDetail, OrderDetailProduct, Footer and AboutUs
  webapp/src/components/About/AboutUs.test.tsx
  webapp/src/components/Footer/Footer.test.tsx
  webapp/src/components/Footer/Footer.tsx
  webapp/src/components/ListProducts.test.tsx
  webapp/src/components/PastOrders/OrderDetailProduct.test.tsx
  webapp/src/components/ProductDetail.test.tsx
  webapp/src/components/ProductDetail.tsx
  webapp/src/shared/shareddtypes.ts
Labels: testing, prototype v1.1

#162 Tests for OrderDetail (100% coverage)
  webapp/src/components/PastOrders/OrderDetail.test.tsx
Labels: testing, prototype v1.1

#163 Tests for Checkout
  webapp/src/components/Checkout/Checkout.test.tsx
  webapp/src/components/Navbar.test.tsx
Labels: testing, prototype v1.1

#165 Tests for CompleteOrder, Cart footer and PaypalCheckoutButton
  webapp/src/components/Cart/Cart.test.tsx
  webapp/src/components/Cart/Footer.test.tsx
  webapp/src/components/Cart/Footer.tsx
  webapp/src/components/Checkout/CompleteOrder.test.tsx
  webapp/src/components/Checkout/CompleteOrder.tsx
  webapp/src/components/Checkout/PaypalCheckoutButton.test.tsx
Labels: testing, prototype v1.1

#170 Improving the general application
  webapp/src/components/Admin/AddProduct.tsx
  webapp/src/components/Checkout/Checkout.test.tsx
  webapp/src/components/Checkout/Checkout.tsx
  webapp/src/components/Checkout/PaypalButton.test.tsx
  webapp/src/components/Checkout/PaypalButton.tsx
  webapp/src/components/HomePage.test.tsx
  webapp/src/components/HomePage.tsx
  webapp/src/components/ListProducts.tsx
  webapp/src/components/LoginButtonContainer.tsx
  webapp/src/components/Navbar.tsx
  webapp/src/components/Order/CartItemCheckout.tsx
  webapp/src/components/Order/Order.tsx
  webapp/src/components/PastOrders/OrderDetail.test.tsx
  webapp/src/components/ProductDetail.tsx
  webapp/src/components/SearchBar.tsx
  webapp/src/components/UserInfoContainer.tsx
  webapp/src/helper/calculateDeliveryCost.ts
Labels: prototype v1.1

#169 Small fixes to the documentation
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/08_concepts.adoc
  docs/11_technical_risks.adoc
  docs/12_glossary.adoc
  docs/images/05_building_blocks_complete.png
  docs/images/08.1-domainModel.png
Labels: documentation v1.1

#164 Bug fixing
  webapp/src/App.tsx
  webapp/src/components/Cart/Item.tsx
  webapp/src/components/Checkout/CompleteOrder.tsx
  webapp/src/components/Checkout/PaypalCheckoutButton.tsx
  webapp/src/components/Order/CartItemCheckout.tsx
  webapp/src/components/Order/Order.tsx
  webapp/src/components/PastOrders/OrderDetail.tsx
  webapp/src/components/PastOrders/OrderDetailProduct.tsx
  webapp/src/components/PastOrders/OrderView.tsx
  webapp/src/components/Sidebar/Sidebar.tsx
  webapp/src/helper/calculateDeliveryCost.ts
Labels: bug
