Repository Arquisoft/dede_en2b, pull requests merged in 2022-04, with the labels that each got.

#94 Documentation 3.1: Updated according to project state
  docs/03_system_scope_and_context.adoc
  docs/images/business_context.png
Labels: documentation, prototype v1.0

#95 Important bug fixes
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/model/Order.java
  restapi-springboot/src/main/resources/application.properties
  webapp/package-lock.json
  webapp/src/api/api.ts
  webapp/src/components/Checkout/CompleteOrder.tsx
  webapp/src/components/LoginButtonContainer.tsx
  webapp/src/components/Navbar.tsx
  webapp/src/components/Order/Order.tsx
  webapp/src/components/PastOrders/ListOrders.tsx
  webapp/src/components/UserInfoContainer.tsx
Labels: bug, prototype v1.0

#97 Code payment
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/Checkout/Checkout.tsx
  webapp/src/components/Checkout/CompleteOrder.tsx
  webapp/src/components/Checkout/PaypalCheckoutButton.tsx
Labels: development, prototype v1.0

#103 Documentation 8
  docs/08_concepts.adoc
  docs/images/08.1-domainModel.png
Labels: documentation, documentation v1.0

#104 Removed some things from the view for next prototype
  webapp/src/App.tsx
  webapp/src/components/PastOrders/OrderView.tsx
Labels: bug, prototype v1.0

#101 Tests (v1)
  webapp/src/App.test.tsx
  webapp/src/components/HomePage.test.tsx
  webapp/src/components/Navbar.test.tsx
  webapp/src/components/PastOrders/OrderView.test.tsx
  webapp/src/components/Product.test.tsx
Labels: prototype v1.0, testing

#106 Part 6
  docs/06_runtime_view.adoc
  docs/images/06.3-LogIn.png
  docs/images/06.3-UserInteraction.png
Labels: documentation, documentation v1.0

#107 Merge documentation to master
  docs/03_system_scope_and_context.adoc
  docs/06_runtime_view.adoc
  docs/08_concepts.adoc
  docs/09_design_decisions.adoc
  docs/11_technical_risks.adoc
  docs/images/06.3-LogIn.png
  docs/images/06.3-UserInteraction.png
  docs/images/08.1-domainModel.png
  docs/images/business_context.png
Labels: documentation, prototype v1.0

#115 Check that user is logged in before checkout
  webapp/package-lock.json
  webapp/src/components/Cart/Footer.css
  webapp/src/components/Cart/Footer.tsx
Labels: development, prototype v1.1

#116 Code payment
  webapp/src/components/Checkout/Checkout.tsx
  webapp/src/components/Checkout/PaypalCheckoutButton.tsx
Labels: prototype v1.1

#117 Order history bug fixed
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/controller/OrderController.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/impl/InsertSampleDataService.java
  webapp/src/components/Checkout/CompleteOrder.tsx
  webapp/src/components/PastOrders/OrderView.tsx
Labels: bug, prototype v1.1

#122 Search bar functionality
  webapp/src/App.tsx
  webapp/src/components/ListProducts.tsx
  webapp/src/components/Navbar.css
  webapp/src/components/Navbar.tsx
  webapp/src/components/SearchBar.tsx
Labels: development, prototype v1.1

#124 Delivery cost fix
  webapp/src/components/Order/Order.tsx
  webapp/src/helper/calculateDeliveryCost.ts
  webapp/src/helper/deliveryAux.ts
  webapp/src/shared/shareddtypes.ts
Labels: bug, prototype v1.1

#125 From code to master, in order to deploy newest version
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/controller/OrderController.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/impl/InsertSampleDataService.java
  webapp/package-lock.json
  webapp/src/App.css
  webapp/src/App.tsx
  webapp/src/components/Cart/Footer.css
  webapp/src/components/Cart/Footer.tsx
  webapp/src/components/Checkout/Checkout.tsx
  webapp/src/components/Checkout/CompleteOrder.tsx
  webapp/src/components/Checkout/PaypalCheckoutButton.tsx
  webapp/src/components/ListProducts.tsx
  webapp/src/components/Navbar.css
  webapp/src/components/Navbar.tsx
  webapp/src/components/Order/Order.tsx
  webapp/src/components/PastOrders/OrderView.tsx
  webapp/src/components/SearchBar.tsx
  webapp/src/components/Sidebar/Sidebar.tsx
  webapp/src/helper/calculateDeliveryCost.ts
  webapp/src/helper/deliveryAux.ts
  webapp/src/shared/shareddtypes.ts
Labels: development

#129 Homepage revamp
  webapp/src/App.tsx
  webapp/src/components/HomePage.css
  webapp/src/components/HomePage.tsx
  webapp/src/components/Homepage/Slider.css
  webapp/src/components/Homepage/Slider.tsx
  webapp/src/helper/sliderData.ts
  webapp/src/img/book1.jpg
  webapp/src/img/mask1.png
  webapp/src/img/shirt1.jpg
  webapp/src/img/slider1.png
  webapp/src/img/slider2.png
  webapp/src/img/slider3.png
Labels: development, prototype v1.1

#131 Product detail page
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/controller/ProductController.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/model/Product.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/ProductService.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/impl/InsertSampleDataService.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/impl/ProductServiceImpl.java
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/Checkout/CompleteOrder.tsx
  webapp/src/components/ListProducts.tsx
  webapp/src/components/PastOrders/OrderView.test.tsx
  webapp/src/components/Product.test.tsx
  webapp/src/components/Product.tsx
  webapp/src/components/ProductDetail.css
  webapp/src/components/ProductDetail.tsx
  webapp/src/shared/shareddtypes.ts
Labels: development, prototype v1.1

#135 Sidebar revamp
  webapp/src/App.css
  webapp/src/App.tsx
  webapp/src/components/Navbar.tsx
Labels: development, prototype v1.1

#138 Added order details view
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/model/Order.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/impl/InsertSampleDataService.java
  webapp/src/App.tsx
  webapp/src/components/Checkout/Checkout.tsx
  webapp/src/components/Checkout/CompleteOrder.tsx
  webapp/src/components/PastOrders/OrderDetail.css
  webapp/src/components/PastOrders/OrderDetail.tsx
  webapp/src/components/PastOrders/OrderDetailProduct.tsx
  webapp/src/components/PastOrders/OrderView.tsx
  webapp/src/helper/calculateDeliveryCost.ts
  webapp/src/shared/shareddtypes.ts
Labels: development, prototype v1.1

#134 documentation
  docs/07_deployment_view.adoc
  docs/images/07_deployment_infraestructure.PNG
Labels: documentation v1.1

#142 About us page
  webapp/src/App.tsx
  webapp/src/components/About/AboutUs.css
  webapp/src/components/About/AboutUs.tsx
  webapp/src/img/icondev.jpg
  webapp/src/img/photoAdrian.jpg
  webapp/src/img/photoDiego.jpg
  webapp/src/img/photoLaura.jpg
Labels: development, prototype v1.1

#140 Reviews
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/controller/RatingsController.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/model/Product.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/model/Rating.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/repository/RatingRepository.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/RatingsService.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/impl/InsertSampleDataService.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/impl/RatingsServiceImpl.java
  webapp/src/api/api.ts
  webapp/src/components/ProductDetail.css
  webapp/src/components/ProductDetail.tsx
  webapp/src/components/UserInfoContainer.tsx
  webapp/src/helper/calculateDeliveryCost.ts
  webapp/src/shared/shareddtypes.ts
Labels: development, prototype v1.1

#141 Footer
  webapp/src/App.tsx
  webapp/src/components/Footer/Footer.css
  webapp/src/components/Footer/Footer.tsx
  webapp/src/img/reactLogo.png
Labels: development, prototype v1.1

#145 Added homepage buttons for each category with filtering
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/controller/ProductController.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/repository/OrderRepository.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/repository/ProductRepository.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/ProductService.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/impl/ProductServiceImpl.java
  webapp/src/api/api.ts
  webapp/src/components/HomePage.tsx
  webapp/src/components/Homepage/Categories.css
  webapp/src/components/Homepage/Categories.tsx
  webapp/src/components/ListProducts.tsx
  webapp/src/hooks/useFetch.tsx
  webapp/src/img/fish.png
  webapp/src/img/fruit.png
  webapp/src/img/meat.png
  webapp/src/img/vegetable.png
Labels: development, prototype v1.1

#150 Documentation 8: Update of every point
  docs/08_concepts.adoc
  docs/images/08.1-domainModel.png
Labels: documentation

#149 No address case
  webapp/src/App.tsx
  webapp/src/components/Cart/Footer.tsx
  webapp/src/components/Checkout/Checkout.tsx
  webapp/src/components/Checkout/PaypalCheckoutButton.tsx
  webapp/src/components/Navbar.tsx
  webapp/src/components/Order/Order.tsx
  webapp/src/components/POD/ChangeData.css
  webapp/src/components/POD/ChangeData.tsx
  webapp/src/components/Sidebar/Sidebar.tsx
  webapp/src/helper/addressHelper.ts
  webapp/src/shared/shareddtypes.ts
Labels: development, prototype v1.1

#152 No address case
  webapp/src/App.tsx
  webapp/src/components/Cart/Footer.tsx
  webapp/src/components/Checkout/Checkout.tsx
  webapp/src/components/Checkout/PaypalCheckoutButton.tsx
  webapp/src/components/Navbar.tsx
  webapp/src/components/Order/Order.tsx
  webapp/src/components/POD/ChangeData.css
  webapp/src/components/POD/ChangeData.tsx
  webapp/src/components/Sidebar/Sidebar.tsx
  webapp/src/helper/addressHelper.ts
  webapp/src/shared/shareddtypes.ts
Labels: development, prototype v1.1

#153 Admin add product
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/controller/ProductController.java
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/Admin/AddProduct.css
  webapp/src/components/Admin/AddProduct.tsx
  webapp/src/components/Navbar.tsx
Labels: development, prototype v1.1
