Repository Arquisoft/dede_en2b, pull requests merged in 2022-03, with the labels that each got.

#48 Products in DB are now shown in home page
  .idea/.gitignore
  .idea/dede_en2b.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  package-lock.json
  package.json
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/controller/ProductController.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/impl/ProductServiceImpl.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/impl/ShoppingCart.java
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/EmailForm.test.tsx
  webapp/src/components/EmailForm.tsx
  webapp/src/components/ProductsTable.tsx
  webapp/src/components/UserList.test.tsx
  webapp/src/components/UserList.tsx
  webapp/src/components/Welcome.test.tsx
  webapp/src/components/Welcome.tsx
  webapp/src/shared/shareddtypes.ts
Labels: development, prototype v0.1

#51 Added order model and service in backend
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/model/Order.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/model/OrderProduct.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/repository/OrderRepository.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/OrderService.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/impl/OrderServiceImpl.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/impl/ShoppingCart.java
Labels: development

#55 Added the home page
  .idea/misc.xml
  package-lock.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/HomePage.css
  webapp/src/components/HomePage.tsx
  webapp/src/components/ProductsTable.tsx
  webapp/src/img/background1.jpg
  webapp/src/img/book1.jpg
  webapp/src/img/mask1.png
  webapp/src/img/shirt1.jpg
Labels: development, prototype v0.1

#56 Shopping cart implemented + Product images shown
  .idea/dede_en2bELBUENODEVD.iml
  .idea/modules.xml
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/model/Product.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/impl/ProductServiceImpl.java
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/Cart/Cart.css
  webapp/src/components/Cart/Cart.tsx
  webapp/src/components/Cart/Footer.tsx
  webapp/src/components/Cart/Item.tsx
  webapp/src/components/CartContext.tsx
  webapp/src/components/ListProducts.tsx
  webapp/src/components/Navbar.tsx
  webapp/src/components/Product.tsx
  webapp/src/components/ProductsTable.tsx
  webapp/src/helper/calculateCartTotal.ts
  webapp/src/hooks/useFetch.tsx
  webapp/src/reducer/CartReducer.ts
  webapp/src/shared/shareddtypes.ts
Labels: development, prototype v0.1

#58 I have reviewed the building block view
  docs/05_building_block_view.adoc
  docs/images/05_building_blocks_complete.png
Labels: documentation

#59 I finished the implementation of the small changes
  .gitignore
  webapp/src/components/Cart/Cart.css
  webapp/src/components/Cart/Cart.tsx
  webapp/src/components/Cart/Footer.tsx
  webapp/src/components/Cart/Item.tsx
  webapp/src/img/emptyshoppingcart.png
Labels: development, prototype v0.1

#61 Code pod login
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/Appbar.tsx
  webapp/src/components/Login.css
  webapp/src/components/LoginButtonContainer.tsx
  webapp/src/components/Navbar.css
  webapp/src/components/Navbar.tsx
  webapp/src/components/ProductsTable.tsx
  webapp/src/components/UserInfoContainer.tsx
Labels: development, prototype v0.1

#62 Part 6 of documentation
  docs/06_runtime_view.adoc
  docs/images/06.1.2-userDiagram.png
Labels: documentation

#63 Documentation
  docs/01_introduction_and_goals.adoc
  docs/03_system_scope_and_context.adoc
  docs/05_building_block_view.adoc
  docs/06_runtime_view.adoc
  docs/10_quality_scenarios.adoc
  docs/images/05_building_blocks_complete.png
  docs/images/06.1.2-userDiagram.png
  docs/images/business_context.png
Labels: documentation

#76 Code sidebar
  webapp/src/App.css
  webapp/src/App.tsx
  webapp/src/components/Cart/Cart.css
  webapp/src/components/HomePage.css
  webapp/src/components/ListProducts.tsx
  webapp/src/components/Navbar.tsx
  webapp/src/components/Product.tsx
  webapp/src/components/Sidebar/Sidebar.tsx
  webapp/src/components/Sidebar/SidebarData.tsx
  webapp/src/index.css
Labels: development, prototype v1.0

#77 Order functionality (Back & front end)
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/controller/OrderController.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/model/Order.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/model/OrderProduct.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/model/Product.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/repository/OrderProductRepository.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/OrderProductService.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/impl/InsertSampleDataService.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/impl/OrderProductServiceImpl.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/impl/OrderServiceImpl.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/service/impl/ProductServiceImpl.java
  webapp/src/api/api.ts
  webapp/src/helper/stringToHexadecimal.ts
  webapp/src/hooks/useOrdersByUser.tsx
  webapp/src/shared/shareddtypes.ts
Labels: development, prototype v1.0

#80 Code checkout v0.5 into code
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/controller/OrderController.java
  webapp/src/App.tsx
  webapp/src/components/Cart/Footer.css
  webapp/src/components/Cart/Footer.tsx
  webapp/src/components/Checkout/Checkout.css
  webapp/src/components/Checkout/Checkout.tsx
  webapp/src/components/Checkout/CompleteOrder.tsx
  webapp/src/components/Navbar.css
  webapp/src/components/Navbar.tsx
  webapp/src/components/Order/CartItemCheckout.css
  webapp/src/components/Order/CartItemCheckout.tsx
  webapp/src/components/Order/Order.css
  webapp/src/components/Order/Order.tsx
  webapp/src/img/receipticon.png
  webapp/src/img/shippingicon.jpg
  webapp/src/index.css
Labels: development, prototype v1.0

#81 Delivery cost added to Order.tsx
  webapp/src/components/Order/Order.tsx
  webapp/src/helper/calculateDeliveryCost.ts
Labels: development

#88 Code checkout
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/controller/OrderController.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/model/Order.java
  restapi-springboot/src/main/java/com/dede_en2b/restapispringboot/model/Product.java
  webapp/src/api/api.ts
  webapp/src/components/Checkout/Checkout.tsx
  webapp/src/components/Checkout/CompleteOrder.css
  webapp/src/components/Checkout/CompleteOrder.tsx
  webapp/src/components/HomePage.css
  webapp/src/index.tsx
Labels: prototype v1.0

#89 Documentation 9: Design decisions
  docs/09_design_decisions.adoc
Labels: documentation, prototype v1.0

#90 Point 11 of the documentation
  .idea/misc.xml
  .idea/workspace.xml
  docs/11_technical_risks.adoc
  restapi-springboot/.idea/.gitignore
  restapi-springboot/.idea/compiler.xml
  restapi-springboot/.idea/encodings.xml
  restapi-springboot/.idea/jarRepositories.xml
  restapi-springboot/.idea/misc.xml
  restapi-springboot/.idea/vcs.xml
  restapi-springboot/target/classes/application.properties
  restapi-springboot/target/classes/com/dede_en2b/restapispringboot/AppContextEventListener.class
  restapi-springboot/target/classes/com/dede_en2b/restapispringboot/RestapiSpringbootApplication.class
  restapi-springboot/target/classes/com/dede_en2b/restapispringboot/controller/OrderController.class
  restapi-springboot/target/classes/com/dede_en2b/restapispringboot/controller/ProductController.class
  restapi-springboot/target/classes/com/dede_en2b/restapispringboot/model/Order.class
  restapi-springboot/target/classes/com/dede_en2b/restapispringboot/model/OrderProduct.class
  restapi-springboot/target/classes/com/dede_en2b/restapispringboot/model/Product.class
  restapi-springboot/target/classes/com/dede_en2b/restapispringboot/repository/OrderProductRepository.class
  restapi-springboot/target/classes/com/dede_en2b/restapispringboot/repository/OrderRepository.class
  restapi-springboot/target/classes/com/dede_en2b/restapispringboot/repository/ProductRepository.class
  restapi-springboot/target/classes/com/dede_en2b/restapispringboot/service/OrderProductService.class
  restapi-springboot/target/classes/com/dede_en2b/restapispringboot/service/OrderService.class
  restapi-springboot/target/classes/com/dede_en2b/restapispringboot/service/ProductService.class
  restapi-springboot/target/classes/com/dede_en2b/restapispringboot/service/impl/InsertSampleDataService.class
  restapi-springboot/target/classes/com/dede_en2b/restapispringboot/service/impl/OrderProductServiceImpl.class
  restapi-springboot/target/classes/com/dede_en2b/restapispringboot/service/impl/OrderServiceImpl.class
  restapi-springboot/target/classes/com/dede_en2b/restapispringboot/service/impl/ProductServiceImpl.class
  restapi-springboot/target/test-classes/com/dede_en2b/restapispringboot/RestapiSpringbootApplicationTests.class
Labels: prototype v1.0, documentation v1.0

#92 Point 11 of the documentation (fixed)
  docs/11_technical_risks.adoc
Labels: prototype v1.0, documentation v1.0
